	#base	"../../_4plug/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_4plug/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_eleven/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_jofrehud/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_tf2hud/resource/ui/huditemeffectmeter_engineer.res"